import fs from "node:fs/promises";
import path from "node:path";
import { sharedDir } from "../paths";

/**
 * Scaffold the shared/devrev.ts helper module for a project.
 * This module provides typed wrappers around the /api/devrev/* endpoints.
 * The PAT is injected by frameMountPlugin as window.__ARCADE_STUDIO_DEVREV_PAT__.
 */
export async function scaffoldDevRevHelper(slug: string): Promise<void> {
  const dir = sharedDir(slug);
  const file = path.join(dir, "devrev.ts");

  // Check if it already exists
  try {
    await fs.access(file);
    return; // Already exists, don't overwrite
  } catch {
    // Doesn't exist, create it
  }

  await fs.mkdir(dir, { recursive: true });

  const content = `/**
 * DevRev API helper - generated by Arcade Studio.
 *
 * This module provides typed wrappers for the DevRev REST API.
 * All functions call /api/devrev/* which proxies to api.devrev.ai with retry logic.
 * The PAT is stored globally in the studio keychain and applied server-side;
 * frames never see the token.
 */

/**
 * Strip null/undefined values from args before sending to API.
 */
function cleanArgs(args: Record<string, unknown>): Record<string, unknown> {
  const cleaned: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(args)) {
    if (v == null) continue;
    if (Array.isArray(v)) {
      const filtered = v.filter((item) => item != null);
      if (filtered.length > 0) cleaned[k] = filtered;
    } else {
      cleaned[k] = v;
    }
  }
  return cleaned;
}

/**
 * Expand dot-notation keys into nested objects.
 * e.g. { "stage.name": ["triage"] } → { stage: { name: ["triage"] } }
 */
function expandDotKeys(args: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(args)) {
    if (key.includes(".")) {
      const parts = key.split(".");
      let current: Record<string, unknown> = result;
      for (let i = 0; i < parts.length - 1; i++) {
        if (!current[parts[i]] || typeof current[parts[i]] !== "object") {
          current[parts[i]] = {};
        }
        current = current[parts[i]] as Record<string, unknown>;
      }
      current[parts[parts.length - 1]] = value;
    } else {
      result[key] = value;
    }
  }
  return result;
}

/**
 * Call a DevRev API endpoint through the studio proxy.
 */
async function callDevRev(
  endpoint: string,
  args: Record<string, unknown>,
  _skipCache?: boolean
): Promise<unknown> {
  const cleaned = cleanArgs(args);
  const expanded = expandDotKeys(cleaned);

  const res = await fetch(\`/api/devrev/\${endpoint}\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(expanded),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(\`DevRev API error: \${res.status} \${text}\`);
  }

  return res.json();
}

// ─── EXPORTED FUNCTIONS ───────────────────────────────────────────

/**
 * List work items (issues, tickets, tasks) with optional filters.
 *
 * @example
 * const data = await listWorks({ type: ["issue"], limit: 20 });
 * const works = (data as any).works || [];
 */
export async function listWorks(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("works.list", args);
}

/**
 * Get a single work item by ID.
 *
 * @example
 * const data = await getWork("ISS-123");
 * const work = (data as any).work;
 */
export async function getWork(id: string): Promise<unknown> {
  return callDevRev("works.get", { id });
}

/**
 * Create a new work item.
 * Requires: title, type, applies_to_part, owned_by
 *
 * @example
 * await createWork({
 *   title: "Fix login bug",
 *   type: "issue",
 *   applies_to_part: "PROD-123",
 *   owned_by: ["DEVU-456"],
 * });
 */
export async function createWork(args: Record<string, unknown>): Promise<unknown> {
  return callDevRev("works.create", args, true);
}

/**
 * Update an existing work item.
 * Requires: id
 *
 * @example
 * await updateWork({
 *   id: "ISS-123",
 *   title: "Updated title",
 *   "stage.name": "done",
 * });
 */
export async function updateWork(args: Record<string, unknown>): Promise<unknown> {
  return callDevRev("works.update", args, true);
}

/**
 * List accounts with optional filters.
 */
export async function listAccounts(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("accounts.list", args);
}

/**
 * List conversations with optional filters.
 */
export async function listConversations(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("conversations.list", args);
}

/**
 * Get the authenticated user's profile.
 *
 * @example
 * const data = await self();
 * const user = (data as any).dev_user;
 */
export async function self(): Promise<unknown> {
  return callDevRev("dev-users.self", {});
}

/**
 * List developer users in the organization.
 */
export async function listDevUsers(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("dev-users.list", args);
}

/**
 * List parts (products, capabilities, features, enhancements).
 */
export async function listParts(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("parts.list", args);
}

/**
 * List RevOrgs (customer organizations).
 */
export async function listRevOrgs(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("rev-orgs.list", args);
}

/**
 * List tags for categorizing work items.
 */
export async function listTags(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("tags.list", args);
}

/**
 * Count work items matching a filter.
 *
 * @example
 * const data = await countWorks({ type: ["issue"] });
 * const count = (data as any).count;
 */
export async function countWorks(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("works.count", args);
}

/**
 * List engagements (meetings, calls, emails).
 */
export async function listEngagements(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("engagements.list", args);
}

/**
 * List links between objects.
 */
export async function listLinks(args: Record<string, unknown> = {}): Promise<unknown> {
  return callDevRev("links.list", args);
}
`;

  await fs.writeFile(file, content);
}
