// studio/src/lift/render.ts
//
// Render a Manifest to (a) markdown for humans and LLM prompt consumption
// and (b) JSON for programmatic consumers. Both are pure string output —
// no I/O. Sections are in the order defined in the design spec §4.2.

import type { Manifest, MappingEntry } from "./types";

export function renderMarkdown(m: Manifest): string {
  const lines: string[] = [];
  const push = (s: string) => lines.push(s);

  push(`# Lift Manifest — ${m.projectSlug}/${m.frameSlug}`);
  push("");
  push(`> Generated by Arcade Studio. Schema version ${m.schemaVersion}. Frame on disk: \`${m.frameAbsPath}\``);
  push("");

  // 1. Intent summary
  push("## Intent");
  push(m.intentSummary || "_(no prompt recorded — intent is implicit from frame code.)_");
  push("");

  // 2. Frame inventory
  push("## Frame inventory");
  if (m.mappings.length === 0 && m.unmapped.length === 0) {
    push("_(Frame imports nothing from arcade roots.)_");
  } else {
    push("| Studio import | Production equivalent | Class | Notes |");
    push("| --- | --- | --- | --- |");
    for (const entry of m.mappings) {
      push(renderMappingRow(entry));
    }
    for (const u of m.unmapped) {
      push(
        `| \`${u.name}\` from \`${u.source}\` | _unmapped_ | judgment | No mapping entry — surface to reviewer; add to mapping table after lift. |`,
      );
    }
  }
  push("");

  // 3. Composite mapping details
  //
  // Skip entries with `production.source === "n/a"` (Studio-only composites
  // like ComputerHeader, ComputerSidebar, CanvasPanel). The inventory row
  // above already says "_no direct equivalent_" and carries the judgment
  // note — a details section for them would just restate the same thing
  // under a misleading "X → n/a" heading.
  const compositesUsed = m.mappings.filter(
    (e) => e.studio.source === "arcade-prototypes" && e.production.source !== "n/a",
  );
  if (compositesUsed.length > 0) {
    push("## Composite mapping details");
    for (const e of compositesUsed) {
      push(`### ${e.studio.name} → ${e.production.name}`);
      if (e.slotNotes.length === 0) {
        push("- _(no structural notes.)_");
      } else {
        for (const n of e.slotNotes) push(`- ${n}`);
      }
      if (e.judgmentNote) push(`- **Judgment:** ${e.judgmentNote}`);
      push("");
    }
  }

  // 4. Token alignment
  push("## Tokens");
  push("Tokens are aligned between arcade-gen and arcade-theme. CSS custom property names carry across. No token remap is required.");
  push("");

  // 5. Scaffolding checklist
  push(`## Production scaffolding (${m.shape})`);
  push("These are the things a Studio frame never covers by itself. Engineer + agent divide between them.");
  push("");
  for (const it of m.scaffolding) {
    const box = it.status === "done" ? "[x]" : it.status === "n/a" ? "[~]" : "[ ]";
    const path = it.pathPattern ? ` — \`${it.pathPattern}\`` : "";
    push(`- ${box} ${it.label}${path}`);
  }
  push("");

  // 6 / 7. Grounding links
  if (m.figmaUrl || m.screenshotUrl) {
    push("## Grounding");
    if (m.figmaUrl) push(`- Figma: ${m.figmaUrl}`);
    if (m.screenshotUrl) push(`- Screenshot: ${m.screenshotUrl}`);
    push("");
  }

  // 8. Agent prompt snippet
  push("## Agent handoff");
  push("Paste the block below into a Claude Code session opened in the `devrev-web` checkout:");
  push("");
  push("```text");
  push(
    `I'm lifting an Arcade Studio frame into devrev-web. Apply MECHANICAL rewrites directly. ` +
      `For STRUCTURAL rewrites, write the new production shape and leave brief comments explaining ` +
      `what changed. For JUDGMENT entries, leave a // TODO: comment with the judgment note and ask ` +
      `me before deciding. Do NOT invent production equivalents for unmapped imports — surface them.\n\n` +
      `Manifest follows.\n\n---\n` +
      `Project/frame: ${m.projectSlug}/${m.frameSlug}\n` +
      `Shape: ${m.shape}\n` +
      `Frame source on disk (Studio user's machine): ${m.frameAbsPath}`,
  );
  push("```");
  push("");

  return lines.join("\n");
}

function renderMappingRow(e: MappingEntry): string {
  const studio = `\`${e.studio.name}\` from \`${e.studio.source}\``;
  const prod =
    e.production.source === "n/a"
      ? "_no direct equivalent_"
      : `\`${e.production.name}\` from \`${e.production.source}\``;
  const notes: string[] = [];
  for (const d of e.propDeltas) {
    if (d.valueMap) {
      const vm = Object.entries(d.valueMap)
        .map(([k, v]) => `${k}→${v}`)
        .join(", ");
      notes.push(`prop \`${d.from}\`: ${vm}`);
    } else if (d.from !== d.to) {
      notes.push(`prop \`${d.from}\`→\`${d.to}\``);
    }
    if (d.note) notes.push(d.note);
  }
  if (e.slotNotes.length > 0) {
    // Composites get a full details section below the inventory table; the
    // row just points readers there. Primitives don't get a details section,
    // so we inline their slot notes in the row itself.
    if (e.studio.source === "arcade-prototypes") {
      notes.push("see composite mapping details");
    } else {
      for (const n of e.slotNotes) notes.push(n);
    }
  }
  if (e.judgmentNote) notes.push(e.judgmentNote);
  const notesText = notes.length === 0 ? "—" : notes.join("; ").replace(/\|/g, "\\|");
  return `| ${studio} | ${prod} | ${e.translationClass} | ${notesText} |`;
}

export function renderJson(m: Manifest): string {
  return JSON.stringify(m, null, 2);
}
