import fs from "node:fs/promises";
import path from "node:path";
import { projectDir, projectMemoryDir } from "./paths";
import { summarizeFrameSource } from "./frameSummary";
import { listComponents } from "./componentStore";

/**
 * Hard cap on the rendered inventory. This file is @-imported into every turn's
 * CLAUDE.md, so its size is prompt cost on every generation. A project with
 * hundreds of frames must degrade to a truncated list, never an unbounded one.
 */
export const INVENTORY_CHAR_CAP = 4_000;

/**
 * Render the "what already exists here" digest. PURE — no IO, no clock, no
 * randomness, so the same project always renders the same file (an unchanged
 * write is a no-op for the reader and keeps diffs quiet).
 *
 * Reuses summarizeFrameSource, the same digest the Computer agent gets, rather
 * than inventing a second frame-description format.
 */
export function renderInventory(args: {
  frames: Array<{ slug: string; source: string }>;
  components: string[];
}): string {
  const header =
    "<!-- INVENTORY.md — what this project already contains. Generated by Studio\n" +
    "     after every frame write; edits here are overwritten. Read this before\n" +
    "     building something new: reuse what's here instead of rebuilding it. -->\n";

  const lines: string[] = [header];

  if (args.frames.length === 0) {
    lines.push("No frames yet — this project is empty.");
  } else {
    lines.push("## Frames already in this project\n");
    let used = 0;
    let listed = 0;
    for (const f of args.frames) {
      // summarizeFrameSource emits "### frame: <name>" + component/text lines.
      const block = summarizeFrameSource(f.slug, f.source);
      if (used + block.length > INVENTORY_CHAR_CAP - 400) break;
      lines.push(block);
      used += block.length;
      listed += 1;
    }
    const remaining = args.frames.length - listed;
    if (remaining > 0) {
      lines.push(`\n(${remaining} more frames not listed — inventory budget reached.)`);
    }
  }

  if (args.components.length > 0) {
    lines.push(
      `\n## Your saved composites\n\n${args.components.join(", ")}\n\n` +
        "Import these from `arcade-prototypes`. Prefer them over hand-rolling the same shape again.",
    );
  }

  const out = lines.join("\n");
  return out.length > INVENTORY_CHAR_CAP
    ? out.slice(0, INVENTORY_CHAR_CAP - 3) + "..."
    : out;
}

/** Read every frame's index.tsx. Missing/unreadable frames are skipped, not fatal. */
async function readFrames(
  projectSlug: string,
): Promise<Array<{ slug: string; source: string }>> {
  const framesDir = path.join(projectDir(projectSlug), "frames");
  let names: string[];
  try {
    names = (await fs.readdir(framesDir, { withFileTypes: true }))
      .filter((d) => d.isDirectory() && !d.name.startsWith("."))
      .map((d) => d.name)
      .sort();
  } catch {
    return []; // no frames dir yet — a brand-new project
  }
  const out: Array<{ slug: string; source: string }> = [];
  for (const slug of names) {
    try {
      const source = await fs.readFile(path.join(framesDir, slug, "index.tsx"), "utf-8");
      out.push({ slug, source });
    } catch {
      // A frame dir with no index.tsx (mid-write, or a stray dir) — skip it.
    }
  }
  return out;
}

/**
 * Regenerate `<project>/memory/INVENTORY.md`. Fire-and-forget safe: never
 * throws. Called post-turn, so a failure must degrade to a stale inventory
 * rather than surfacing to the designer.
 */
export async function writeInventory(projectSlug: string): Promise<void> {
  try {
    const [frames, components] = await Promise.all([
      readFrames(projectSlug),
      listComponents().catch(() => []),
    ]);
    const body = renderInventory({
      frames,
      components: components.map((c) => c.name).sort(),
    });
    const dir = projectMemoryDir(projectSlug);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(path.join(dir, "INVENTORY.md"), body, "utf-8");
  } catch (err) {
    console.warn(
      `[studio] inventory write failed for ${projectSlug}:`,
      err instanceof Error ? err.message : String(err),
    );
  }
}
