import fs from "node:fs/promises";
import path from "node:path";
import { projectDir, projectMemoryDir } from "./paths";
import { summarizeFrameSource } from "./frameSummary";

/**
 * Hard cap on the rendered inventory. This file is @-imported into every turn's
 * CLAUDE.md, so its size is prompt cost on every generation. A project with
 * hundreds of frames must degrade to a truncated list, never an unbounded one.
 */
export const INVENTORY_CHAR_CAP = 4_000;

/**
 * Render the "what already exists here" digest. PURE — no IO, no clock, no
 * randomness, so the same project always renders the same file (an unchanged
 * write is a no-op for the reader and keeps diffs quiet).
 *
 * Reuses summarizeFrameSource, the same digest the Computer agent gets, rather
 * than inventing a second frame-description format.
 */
export function renderInventory(args: {
  frames: Array<{ slug: string; source: string }>;
  components: string[];
}): string {
  const header =
    "<!-- INVENTORY.md — what this project already contains. Generated by Studio\n" +
    "     after every frame write; edits here are overwritten. Read this before\n" +
    "     building something new: reuse what's here instead of rebuilding it. -->\n";

  const lines: string[] = [header];

  if (args.frames.length === 0) {
    lines.push("No frames yet — this project is empty.");
  } else {
    lines.push("## Frames already in this project\n");
    let used = 0;
    let listed = 0;
    for (const f of args.frames) {
      // summarizeFrameSource emits "### frame: <name>" + component/text lines.
      const block = summarizeFrameSource(f.slug, f.source);
      if (used + block.length > INVENTORY_CHAR_CAP - 400) break;
      lines.push(block);
      used += block.length;
      listed += 1;
    }
    const remaining = args.frames.length - listed;
    if (remaining > 0) {
      lines.push(`\n(${remaining} more frames not listed — inventory budget reached.)`);
    }
  }

  if (args.components.length > 0) {
    lines.push(
      `\n## Your saved composites\n\n${args.components.join(", ")}\n\n` +
        "Import these from `arcade-prototypes`. Prefer them over hand-rolling the same shape again.",
    );
  }

  const out = lines.join("\n");
  return out.length > INVENTORY_CHAR_CAP
    ? out.slice(0, INVENTORY_CHAR_CAP - 3) + "..."
    : out;
}

/**
 * Structured inventory for the Memory panel. The panel must NOT render
 * `INVENTORY.md` — that file is prompt text for the agent (markdown headings,
 * a full visible-text dump) and reads as a wall of code when shown to a
 * designer. Same source data, shaped for a UI instead.
 */
export interface InventoryFrameView {
  slug: string;
  /** Kit composites/components this frame imports, deduped. */
  components: string[];
}
export interface InventoryView {
  frames: InventoryFrameView[];
  composites: string[];
}

/** Component identifiers a frame imports — PascalCase named imports only. */
function importedComponents(src: string): string[] {
  const seen = new Set<string>();
  const importRe = /import\s*\{([^}]*)\}\s*from\s*["'][^"']*["']/g;
  let m: RegExpExecArray | null;
  while ((m = importRe.exec(src)) !== null) {
    for (const raw of m[1].split(",")) {
      const name = raw.trim().split(/\s+as\s+/)[0].trim();
      if (name && /^[A-Z]/.test(name)) seen.add(name);
    }
  }
  return [...seen].sort();
}

/**
 * Read the same on-disk state `writeInventory` renders, but return DATA.
 * Never throws — an unreadable project degrades to an empty view so the panel
 * still loads.
 */
export async function readInventoryView(projectSlug: string): Promise<InventoryView> {
  try {
    const listComposites = async (): Promise<string[]> => {
      try {
        // Lazy for the same reason as in writeInventory: componentStore pulls
        // esbuild in through packFromSource.
        const { listComponents } = await import("./componentStore");
        return (await listComponents()).map((c) => c.name).sort();
      } catch {
        return [];
      }
    };
    const [frames, composites] = await Promise.all([
      readFrames(projectSlug),
      listComposites(),
    ]);
    return {
      frames: frames.map((f) => ({ slug: f.slug, components: importedComponents(f.source) })),
      composites,
    };
  } catch {
    return { frames: [], composites: [] };
  }
}

/** Read every frame's index.tsx. Missing/unreadable frames are skipped, not fatal. */
async function readFrames(
  projectSlug: string,
): Promise<Array<{ slug: string; source: string }>> {
  const framesDir = path.join(projectDir(projectSlug), "frames");
  let names: string[];
  try {
    names = (await fs.readdir(framesDir, { withFileTypes: true }))
      .filter((d) => d.isDirectory() && !d.name.startsWith("."))
      .map((d) => d.name)
      .sort();
  } catch {
    return []; // no frames dir yet — a brand-new project
  }
  const out: Array<{ slug: string; source: string }> = [];
  for (const slug of names) {
    try {
      const source = await fs.readFile(path.join(framesDir, slug, "index.tsx"), "utf-8");
      out.push({ slug, source });
    } catch {
      // A frame dir with no index.tsx (mid-write, or a stray dir) — skip it.
    }
  }
  return out;
}

/**
 * Regenerate `<project>/memory/INVENTORY.md`. Fire-and-forget safe: never
 * throws. Called post-turn, so a failure must degrade to a stale inventory
 * rather than surfacing to the designer.
 */
export async function writeInventory(projectSlug: string): Promise<void> {
  try {
    // Lazy import: componentStore pulls in the esbuild-backed bundler through
    // packFromSource. A static import would drag esbuild into every module that
    // imports projects.ts/chat.ts, which breaks 12 test files under jsdom
    // (esbuild's TextEncoder invariant fails there). Loading it here keeps the
    // dependency at the call site.
    const listComponentNames = async (): Promise<string[]> => {
      try {
        const { listComponents } = await import("./componentStore");
        return (await listComponents()).map((c) => c.name).sort();
      } catch {
        return [];
      }
    };

    const [frames, components] = await Promise.all([
      readFrames(projectSlug),
      listComponentNames(),
    ]);
    const body = renderInventory({
      frames,
      components,
    });
    const dir = projectMemoryDir(projectSlug);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(path.join(dir, "INVENTORY.md"), body, "utf-8");
  } catch (err) {
    console.warn(
      `[studio] inventory write failed for ${projectSlug}:`,
      err instanceof Error ? err.message : String(err),
    );
  }
}
