import type { SynthesizedSections, TokenEntry } from "./types";

export interface RenderSource {
  fileKey: string;
  fileName?: string;
  scannedAt: string;
}

const IDENTITY_WORD_CAP = 80;
const COMPONENT_CAP = 50;
const EMPTY_SENTINEL = "_(none detected)_";

export function renderDesignMd(s: SynthesizedSections, source: RenderSource): string {
  const lines: string[] = [];
  lines.push("# Design system (from Figma)");
  lines.push("");
  lines.push(
    `<!-- Generated by Arcade Studio on ${source.scannedAt} from Figma file ${source.fileKey}.`,
  );
  lines.push(`     Edit freely — future Studio runs won't overwrite this file. -->`);
  lines.push("");

  lines.push("## Identity");
  lines.push(clampIdentity(s.identity));
  lines.push("");

  lines.push("## Colors");
  lines.push(...renderTokenSection(s.colors.entries));
  lines.push("");

  lines.push("## Typography");
  lines.push(...renderTokenSection(s.typography.entries));
  lines.push("");

  lines.push("## Spacing");
  lines.push(s.spacing.scale.length ? `Scale: ${s.spacing.scale.join(", ")}` : EMPTY_SENTINEL);
  lines.push("");

  lines.push("## Radii");
  lines.push(s.radii.scale.length ? `Scale: ${s.radii.scale.join(", ")}` : EMPTY_SENTINEL);
  lines.push("");

  lines.push("## Shadows");
  if (s.shadows.items.length === 0) lines.push(EMPTY_SENTINEL);
  else for (const sh of s.shadows.items) lines.push(`- ${sh.name}: ${sh.css}`);
  lines.push("");

  lines.push("## Components");
  const comps = s.components.slice(0, COMPONENT_CAP);
  lines.push(comps.length ? comps.join(", ") : EMPTY_SENTINEL);
  lines.push("");

  return lines.join("\n");
}

function renderTokenSection(entries: TokenEntry[]): string[] {
  if (entries.length === 0) return [EMPTY_SENTINEL];
  return entries.map((e) => `- ${e.role} — ${e.name}: ${e.value}`);
}

function clampIdentity(text: string): string {
  const words = text.trim().split(/\s+/);
  if (words.length <= IDENTITY_WORD_CAP) return text.trim();
  const clamped = words.slice(0, IDENTITY_WORD_CAP).join(" ");
  // Trim back to the last sentence boundary inside the cap so we don't end mid-phrase.
  const sentenceEnd = clamped.match(/^(.*[.!?])\s+\S+/);
  return (sentenceEnd ? sentenceEnd[1] : clamped).trim();
}
