function redactToken(text: string, token: string): string {
  if (!text) return text;
  let out = text;
  if (token && token.length >= 4) out = out.split(token).join("[REDACTED]");
  return out.replace(/\b[A-Za-z0-9]{20,}\b/g, (match) =>
    match === "REDACTED" ? match : "[REDACTED]",
  );
}

interface DeploymentFile {
  file: string;
  data: string;
}

interface DeploymentResult {
  id: string;
  url: string;
  readyState: "READY" | "ERROR" | "QUEUED" | "BUILDING";
}

export async function deployToVercel({
  name,
  files,
  token,
  teamId,
}: {
  name: string;
  files: DeploymentFile[];
  token: string;
  teamId?: string;
}): Promise<DeploymentResult> {
  const url = teamId
    ? `https://api.vercel.com/v13/deployments?teamId=${teamId}`
    : "https://api.vercel.com/v13/deployments";

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      name,
      files,
      projectSettings: { framework: null },
      target: "production",
    }),
  });

  if (!response.ok) {
    const raw = await response.text();
    const sanitized = redactToken(raw, token);
    throw new Error(`Vercel deploy failed: ${response.status} ${sanitized}`);
  }

  const result = await response.json();
  return {
    id: result.id,
    url: result.url,
    readyState: result.readyState || "QUEUED",
  };
}

export async function validateVercelToken(token: string): Promise<boolean> {
  try {
    const response = await fetch("https://api.vercel.com/v2/user", {
      headers: { "Authorization": `Bearer ${token}` },
    });
    return response.ok;
  } catch {
    return false;
  }
}

// Team/Pro Vercel accounts enable "Vercel Authentication" by default on every
// new project — every deployment then serves an SSO login wall instead of the
// actual site, which looks to the user like a broken/blank page. Frames
// generated by Studio are meant to be shared publicly, so we ensure the
// project exists AND is unprotected before deploying. Doing this first (not
// after) means the deployment is created under an already-unprotected project
// — no race window where the first request hits the SSO wall.
//
// We call this "ensureUnprotectedProject" because it both creates the project
// if missing (handling the 409 "already exists" case) and patches protection
// off. Running this repeatedly for the same name is safe.
export async function ensureUnprotectedProject({
  projectName,
  token,
  teamId,
}: {
  projectName: string;
  token: string;
  teamId?: string;
}): Promise<void> {
  const qs = teamId ? `?teamId=${teamId}` : "";

  // Try to create the project first. If it already exists Vercel returns 409;
  // we swallow that one case and fall through to the PATCH. Any other
  // non-2xx is a real error and bubbles up — we used to "best-effort warn"
  // here and it hid the real failure for a deploy cycle.
  //
  // The Create Project endpoint does NOT accept ssoProtection /
  // passwordProtection as properties — it rejects the request with
  // "Invalid request: should NOT have additional property `passwordProtection`".
  // Those fields only exist on the PATCH (Update Project). So we create
  // with just name + framework, then PATCH protection off separately.
  const createRes = await fetch(`https://api.vercel.com/v10/projects${qs}`, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      name: projectName,
      framework: null,
    }),
  });

  if (!createRes.ok && createRes.status !== 409) {
    const raw = await createRes.text().catch(() => "");
    throw new Error(
      `Vercel project create failed: ${createRes.status} ${redactToken(raw, token)}`,
    );
  }
  console.log(
    `[vercel] ensureUnprotectedProject(${projectName}): create status=${createRes.status}`,
  );

  // Always PATCH to make sure protection is off. Creation with
  // ssoProtection: null is rejected by some plans that enforce a team-wide
  // default; the PATCH is the actual workhorse. This also turns off
  // protection for pre-existing projects users may have created earlier.
  const patchRes = await fetch(
    `https://api.vercel.com/v9/projects/${projectName}${qs}`,
    {
      method: "PATCH",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        ssoProtection: null,
        passwordProtection: null,
      }),
    },
  );

  if (!patchRes.ok) {
    const raw = await patchRes.text().catch(() => "");
    throw new Error(
      `Vercel project protection-disable failed: ${patchRes.status} ${redactToken(raw, token)}`,
    );
  }

  // After the PATCH we re-read the project and log its protection fields.
  // This is how we'll know whether team-level defaults are silently
  // overriding our null writes — Vercel returns 2xx on the PATCH but keeps
  // ssoProtection populated. If this log shows non-null values, the fix
  // needs to happen in the Vercel dashboard (team settings), not here.
  const getRes = await fetch(
    `https://api.vercel.com/v9/projects/${projectName}${qs}`,
    { headers: { "Authorization": `Bearer ${token}` } },
  );
  if (getRes.ok) {
    const proj: any = await getRes.json();
    console.log(
      `[vercel] ensureUnprotectedProject(${projectName}): post-PATCH ` +
        `ssoProtection=${JSON.stringify(proj.ssoProtection)} ` +
        `passwordProtection=${JSON.stringify(proj.passwordProtection)}`,
    );
  }
}
